# Generated by Django 3.1.6 on 2021-06-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210607_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='link',
            field=models.CharField(max_length=1000, null=True, verbose_name='Link'),
        ),
    ]
