# Generated by Django 3.1.6 on 2021-06-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='link',
            field=models.FileField(null=True, upload_to='', verbose_name='Ses'),
        ),
    ]
