# Generated by Django 3.1.6 on 2021-06-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210608_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='link',
            new_name='audio',
        ),
        migrations.AddField(
            model_name='music',
            name='picture',
            field=models.FileField(null=True, upload_to='', verbose_name='Fotoğraf'),
        ),
    ]
