# Generated by Django 3.1.6 on 2021-06-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210608_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf'),
        ),
    ]
