# Generated by Django 3.1.6 on 2021-06-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210608_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='piece',
            field=models.CharField(max_length=60, null=True, verbose_name='Eser '),
        ),
    ]
