# Generated by Django 3.1.6 on 2021-02-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='note',
            name='note_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Notunuza Fotoraf Ekleyin'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Başlık '),
        ),
    ]
